#!/bin/bash
# 2016-07-22
if [[ $# -lt 1 ]];then
  echo "USAGE: `basename $0` [-c command_in_quote] [-f listfile]"
  echo "HELP: `basename $0` -h"
  echo "VERSION: `basename $0` -v"
  exit 1
fi

while getopts "hvc:f:" arg
do
  case $arg in
    h)
      echo "dirqsub 1.0"
      echo "(2016-07-21)"
      echo "USAGE:`basename $0` [-n taskname] [-c command_in_quote] [-p 2] [-m 16gb] [-f listfile]"
      exit 1
      ;;
    v)
      echo "myqsub version 1.0"
      exit 1
      ;;
    c)
      command=$OPTARG
      ;;
    f)
      file=$OPTARG
      ;;
    ?)
      echo "unkonw argument"
      echo "please see help using -h"
      exit 1
      ;;
  esac
done

file=${file:?file?}
command=${command:?command?}

cat ${file} | while read LINE
do
  cd $LINE
  pwd
  echo $command
  eval $command
  cd ..
done
